-- default tablespace　を確認する
SELECT property_value 
FROM database_properties 
WHERE property_name = 'DEFAULT_PERMANENT_TABLESPACE'
;

PROPERTY_VALUE
----------------
SYSTEM

-- default tablespace　を変更する
ALTER DATABASE DEFAULT TABLESPACE users;

-- アーカイブログモードを確認する
SELECT log_mode
FROM v$database;

LOG_MODE
----------
ARCHIVELOG

-- アーカイブログモードに変更する
alter database archivelog;

-- データベースのオープンモードを確認する
SQL> SELECT open_mode FROM v$database;

OPEN_MODE
------------------
READ WRITE

-- 表領域情報
SET LINESIZE 200
SET PAGESIZE 1000
COL TABLESPACE_NAME FOR A12
COL FILE_NAME FOR A36
COL CONTENTS FOR A10
COL BLOCK_SIZE FOR 9999
COL EXTENT_MANAGEMENT FOR A18
COL ALLOCATION_TYPE FOR A15
COL SEGMENT_SPACE_MANAGEMENT FOR A23
COL BIGFILE FOR A7
COL AUTOEXTENSIBLE FOR A13
COL M_MAXBYTES FOR 99999999999999
COL INCREMENT_BY FOR 99999999999999 
SELECT TABLESPACE_NAME, FILE_NAME, CONTENTS, BLOCK_SIZE, EXTENT_MANAGEMENT
, ALLOCATION_TYPE, SEGMENT_SPACE_MANAGEMENT, BIGFILE, AUTOEXTENSIBLE
, ROUND(M_MAXBYTES/(1024*1024)) AS M_MAXBYTES_MB
, ROUND((INCREMENT_BY*BLOCK_SIZE)/(1024*1024)) AS INCREMENT_BY_MB
FROM (
  SELECT df.TABLESPACE_NAME                
  ,df.FILE_NAME
  ,ts.CONTENTS
  ,ts.BLOCK_SIZE
  ,ts.EXTENT_MANAGEMENT
  ,ts.ALLOCATION_TYPE
  ,ts.SEGMENT_SPACE_MANAGEMENT
  ,ts.BIGFILE
  ,df.AUTOEXTENSIBLE
  ,df.MAXBYTES AS M_MAXBYTES
  ,df.INCREMENT_BY
  FROM DBA_DATA_FILES df
  JOIN DBA_TABLESPACES ts ON df.TABLESPACE_NAME = ts.TABLESPACE_NAME
  UNION
  SELECT tf.TABLESPACE_NAME
  ,tf.FILE_NAME
  ,ts.CONTENTS
  ,ts.BLOCK_SIZE
  ,ts.EXTENT_MANAGEMENT
  ,ts.ALLOCATION_TYPE
  ,ts.SEGMENT_SPACE_MANAGEMENT
  ,ts.BIGFILE
  ,tf.AUTOEXTENSIBLE
  ,tf.MAXBYTES AS M_MAXBYTES
  ,tf.INCREMENT_BY
  FROM DBA_TEMP_FILES tf
  JOIN DBA_TABLESPACES ts ON tf.TABLESPACE_NAME = ts.TABLESPACE_NAME
  UNION
  SELECT ts.TABLESPACE_NAME
  ,NULL AS FILE_NAME
  ,ts.CONTENTS
  ,ts.BLOCK_SIZE
  ,ts.EXTENT_MANAGEMENT
  ,ts.ALLOCATION_TYPE
  ,ts.SEGMENT_SPACE_MANAGEMENT
  ,ts.BIGFILE
  ,NULL AS AUTOEXTENSIBLE
  ,NULL AS M_MAXBYTES
  ,NULL AS INCREMENT_BY
  FROM DBA_TABLESPACES ts
) 
WHERE FILE_NAME IS NOT NULL
AND CONTENTS IS NOT NULL
AND BLOCK_SIZE IS NOT NULL
AND EXTENT_MANAGEMENT IS NOT NULL
AND ALLOCATION_TYPE IS NOT NULL
AND SEGMENT_SPACE_MANAGEMENT IS NOT NULL
AND BIGFILE IS NOT NULL
AND AUTOEXTENSIBLE IS NOT NULL
AND M_MAXBYTES IS NOT NULL
AND INCREMENT_BY IS NOT NULL
ORDER BY TABLESPACE_NAME
;
------------

SET LINESIZE 200
SET PAGESIZE 1000
COL TABLESPACE_NAME FOR A12
COL FILE_NAME FOR A36
COL CONTENTS FOR A10
COL BLOCK_SIZE FOR 9999
COL EXTENT_MANAGEMENT FOR A18
COL ALLOCATION_TYPE FOR A15
COL SEGMENT_SPACE_MANAGEMENT FOR A23
COL BIGFILE FOR A7
COL "自動拡張" FOR A13
COL M_MAXBYTES FOR 99999999999999
COL INCREMENT_BY FOR 99999999999999
--  
SELECT *
FROM (
  SELECT df.TABLESPACE_NAME                
  ,df.FILE_NAME
  ,ts.CONTENTS
  ,ts.BLOCK_SIZE
  ,ts.EXTENT_MANAGEMENT
  ,ts.ALLOCATION_TYPE
  ,ts.SEGMENT_SPACE_MANAGEMENT
  ,ts.BIGFILE
  ,df.AUTOEXTENSIBLE AS "自動拡張"
  ,ROUND(df.MAXBYTES/(1024*1024)) AS M_MAXBYTES_MB
  ,ROUND((df.INCREMENT_BY*ts.BLOCK_SIZE)/(1024*1024)) AS INCREMENT_BY_MB
  FROM DBA_DATA_FILES df
  JOIN DBA_TABLESPACES ts ON df.TABLESPACE_NAME = ts.TABLESPACE_NAME
  UNION
  SELECT tf.TABLESPACE_NAME
  ,tf.FILE_NAME
  ,ts.CONTENTS
  ,ts.BLOCK_SIZE
  ,ts.EXTENT_MANAGEMENT
  ,ts.ALLOCATION_TYPE
  ,ts.SEGMENT_SPACE_MANAGEMENT
  ,ts.BIGFILE
  ,tf.AUTOEXTENSIBLE AS "自動拡張"
  ,ROUND(tf.MAXBYTES/(1024*1024)) AS M_MAXBYTES_MB
  ,ROUND((tf.INCREMENT_BY*ts.BLOCK_SIZE)/(1024*1024)) AS INCREMENT_BY_MB
  FROM DBA_TEMP_FILES tf
  JOIN DBA_TABLESPACES ts ON tf.TABLESPACE_NAME = ts.TABLESPACE_NAME
  UNION
  SELECT ts.TABLESPACE_NAME
  ,NULL AS FILE_NAME
  ,ts.CONTENTS
  ,ts.BLOCK_SIZE
  ,ts.EXTENT_MANAGEMENT
  ,ts.ALLOCATION_TYPE
  ,ts.SEGMENT_SPACE_MANAGEMENT
  ,ts.BIGFILE
  ,NULL AS "自動拡張"
  ,NULL AS M_MAXBYTES_MB
  ,NULL AS INCREMENT_BY_MB
  FROM DBA_TABLESPACES ts
) 
WHERE FILE_NAME IS NOT NULL
AND CONTENTS IS NOT NULL
AND BLOCK_SIZE IS NOT NULL
AND EXTENT_MANAGEMENT IS NOT NULL
AND ALLOCATION_TYPE IS NOT NULL
AND SEGMENT_SPACE_MANAGEMENT IS NOT NULL
AND BIGFILE IS NOT NULL
AND "自動拡張" IS NOT NULL
AND M_MAXBYTES_MB IS NOT NULL
AND INCREMENT_BY_MB IS NOT NULL
ORDER BY TABLESPACE_NAME;

